/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedRawMaterialsRouteImport } from './routes/_authed/raw-materials'
import { Route as AuthedPurchaseOrdersRouteImport } from './routes/_authed/purchase-orders'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedProductionRouteImport } from './routes/_authed/production'
import { Route as AuthedPostersRouteImport } from './routes/_authed/posters'
import { Route as AuthedOrdersRouteImport } from './routes/_authed/orders'
import { Route as AuthedMaterialsRouteImport } from './routes/_authed/materials'
import { Route as AuthedLabelsRouteImport } from './routes/_authed/labels'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed/invoices'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCustomersRouteImport } from './routes/_authed/customers'
import { Route as AuthedBarcodesRouteImport } from './routes/_authed/barcodes'
import { Route as AuthedBackupRouteImport } from './routes/_authed/backup'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedAlertsRouteImport } from './routes/_authed/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRawMaterialsRoute = AuthedRawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersRoute = AuthedPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductionRoute = AuthedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostersRoute = AuthedPostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersRoute = AuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaterialsRoute = AuthedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsRoute = AuthedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBarcodesRoute = AuthedBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupRoute = AuthedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/backup': typeof AuthedBackupRoute
  '/barcodes': typeof AuthedBarcodesRoute
  '/customers': typeof AuthedCustomersRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inventory': typeof AuthedInventoryRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/labels': typeof AuthedLabelsRoute
  '/materials': typeof AuthedMaterialsRoute
  '/orders': typeof AuthedOrdersRoute
  '/posters': typeof AuthedPostersRoute
  '/production': typeof AuthedProductionRoute
  '/products': typeof AuthedProductsRoute
  '/purchase-orders': typeof AuthedPurchaseOrdersRoute
  '/raw-materials': typeof AuthedRawMaterialsRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/suppliers': typeof AuthedSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/backup': typeof AuthedBackupRoute
  '/barcodes': typeof AuthedBarcodesRoute
  '/customers': typeof AuthedCustomersRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inventory': typeof AuthedInventoryRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/labels': typeof AuthedLabelsRoute
  '/materials': typeof AuthedMaterialsRoute
  '/orders': typeof AuthedOrdersRoute
  '/posters': typeof AuthedPostersRoute
  '/production': typeof AuthedProductionRoute
  '/products': typeof AuthedProductsRoute
  '/purchase-orders': typeof AuthedPurchaseOrdersRoute
  '/raw-materials': typeof AuthedRawMaterialsRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/suppliers': typeof AuthedSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/backup': typeof AuthedBackupRoute
  '/_authed/barcodes': typeof AuthedBarcodesRoute
  '/_authed/customers': typeof AuthedCustomersRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/labels': typeof AuthedLabelsRoute
  '/_authed/materials': typeof AuthedMaterialsRoute
  '/_authed/orders': typeof AuthedOrdersRoute
  '/_authed/posters': typeof AuthedPostersRoute
  '/_authed/production': typeof AuthedProductionRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/purchase-orders': typeof AuthedPurchaseOrdersRoute
  '/_authed/raw-materials': typeof AuthedRawMaterialsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/suppliers': typeof AuthedSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/audit'
    | '/backup'
    | '/barcodes'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/labels'
    | '/materials'
    | '/orders'
    | '/posters'
    | '/production'
    | '/products'
    | '/purchase-orders'
    | '/raw-materials'
    | '/reports'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/audit'
    | '/backup'
    | '/barcodes'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/labels'
    | '/materials'
    | '/orders'
    | '/posters'
    | '/production'
    | '/products'
    | '/purchase-orders'
    | '/raw-materials'
    | '/reports'
    | '/settings'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/alerts'
    | '/_authed/audit'
    | '/_authed/backup'
    | '/_authed/barcodes'
    | '/_authed/customers'
    | '/_authed/dashboard'
    | '/_authed/inventory'
    | '/_authed/invoices'
    | '/_authed/labels'
    | '/_authed/materials'
    | '/_authed/orders'
    | '/_authed/posters'
    | '/_authed/production'
    | '/_authed/products'
    | '/_authed/purchase-orders'
    | '/_authed/raw-materials'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/_authed/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/raw-materials': {
      id: '/_authed/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthedRawMaterialsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders': {
      id: '/_authed/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthedPurchaseOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/production': {
      id: '/_authed/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthedProductionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posters': {
      id: '/_authed/posters'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof AuthedPostersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/materials': {
      id: '/_authed/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthedMaterialsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels': {
      id: '/_authed/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthedLabelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/barcodes': {
      id: '/_authed/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof AuthedBarcodesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backup': {
      id: '/_authed/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthedBackupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedBackupRoute: typeof AuthedBackupRoute
  AuthedBarcodesRoute: typeof AuthedBarcodesRoute
  AuthedCustomersRoute: typeof AuthedCustomersRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedLabelsRoute: typeof AuthedLabelsRoute
  AuthedMaterialsRoute: typeof AuthedMaterialsRoute
  AuthedOrdersRoute: typeof AuthedOrdersRoute
  AuthedPostersRoute: typeof AuthedPostersRoute
  AuthedProductionRoute: typeof AuthedProductionRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedPurchaseOrdersRoute: typeof AuthedPurchaseOrdersRoute
  AuthedRawMaterialsRoute: typeof AuthedRawMaterialsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedBackupRoute: AuthedBackupRoute,
  AuthedBarcodesRoute: AuthedBarcodesRoute,
  AuthedCustomersRoute: AuthedCustomersRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedLabelsRoute: AuthedLabelsRoute,
  AuthedMaterialsRoute: AuthedMaterialsRoute,
  AuthedOrdersRoute: AuthedOrdersRoute,
  AuthedPostersRoute: AuthedPostersRoute,
  AuthedProductionRoute: AuthedProductionRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedPurchaseOrdersRoute: AuthedPurchaseOrdersRoute,
  AuthedRawMaterialsRoute: AuthedRawMaterialsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
